export { install, findAnchorFiles, type InstallOptions, type InstallResult } from './install.js'
export { uninstall, type UninstallOptions, type UninstallResult } from './uninstall.js'
export { status, formatStatus, type StatusOptions, type StatusReport } from './status.js'
export { doctor, formatDoctor, type DoctorReport } from './doctor.js'
export { resolveTarget, candidateAppRoots, APPIMAGE_HELP, type OrcaTarget } from './locate.js'
export { injectScriptBlock, removeScriptBlocks, countInjectedBlocks } from '@mlp/orca-patch-core'
export { ExitCode, PatcherError } from '@mlp/orca-patch-core'
export { readUserConfig, writeUserConfig, type UserConfig } from '@mlp/orca-patch-core'
export type { CommonOptions, Logger, CommandRunner } from './context.js'
export * from './constants.js'
